# -*- coding: utf-8 -*-
"""sadia tamanna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caMzxp-q4C2jbcDgkkArHhei6b3oXZ2R
"""

{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "qQ7kOZHHIJuV"
      },
      "outputs": [],
      "source": [
        "import heapq\n",
        "import networkx as nx\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "landmarks = {\n",
        "    \"Jeonju\": {\n",
        "        \"Daejeon\": 62,\n",
        "        \"Gwangju\": 80,\n",
        "        \"Jinju\": 116\n",
        "    },\n",
        "    \"Jinju\": {\"Jeonju\": 116, \"Busan\": 86},\n",
        "    \"Gwangju\": {\"Jeonju\": 80, \"Daejeon\": 142},\n",
        "    \"Busan\": {\n",
        "        \"Jinju\": 86,\n",
        "        \"Ulsan\": 46,\n",
        "        \"Jeju\": 299\n",
        "    },\n",
        "    \"Ulsan\": {\"Daejeon\": 197, \"Busan\": 46},\n",
        "    \"Jeju\": {\"Busan\": 299},\n",
        "    \"Daejeon\": {\n",
        "        \"Jeonju\": 62,\n",
        "        \"Ulsan\": 197,\n",
        "        \"Gwangju\": 142\n",
        "    }\n",
        "}"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import heapq\n",
        "import networkx as nx\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# Landmarks dictionary\n",
        "data = {\n",
        "    \"Jeonju\": {\"Daejeon\": 62, \"Gwangju\": 80, \"Jinju\": 116},\n",
        "    \"Jinju\": {\"Jeonju\": 116, \"Busan\": 86},\n",
        "    \"Gwangju\": {\"Jeonju\": 80, \"Daejeon\": 142},\n",
        "    \"Busan\": {\"Jinju\": 86, \"Ulsan\": 46, \"Jeju\": 299},\n",
        "    \"Ulsan\": {\"Daejeon\": 197, \"Busan\": 46},\n",
        "    \"Jeju\": {\"Busan\": 299},\n",
        "    \"Daejeon\": {\"Jeonju\": 62, \"Ulsan\": 197, \"Gwangju\": 142}\n",
        "}\n",
        "\n",
        "# Function to implement Dijkstra's algorithm\n",
        "def dijkstra(graph, start, end):\n",
        "    pq = []  # Priority queue\n",
        "    heapq.heappush(pq, (0, start))  # (distance, node)\n",
        "    distances = {node: float('inf') for node in graph}\n",
        "    distances[start] = 0\n",
        "    previous_nodes = {node: None for node in graph}\n",
        "\n",
        "    while pq:\n",
        "        current_distance, current_node = heapq.heappop(pq)\n",
        "\n",
        "        if current_distance > distances[current_node]:\n",
        "            continue\n",
        "\n",
        "        for neighbor, weight in graph[current_node].items():\n",
        "            distance = current_distance + weight\n",
        "            if distance < distances[neighbor]:\n",
        "                distances[neighbor] = distance\n",
        "                previous_nodes[neighbor] = current_node\n",
        "                heapq.heappush(pq, (distance, neighbor))\n",
        "\n",
        "    # Reconstruct the shortest path\n",
        "    path = []\n",
        "    current = end\n",
        "    while current is not None:\n",
        "        path.append(current)\n",
        "        current = previous_nodes[current]\n",
        "    path.reverse()\n",
        "\n",
        "    return distances[end], path\n",
        "\n",
        "# Create and plot the graph\n",
        "def plot_graph(graph):\n",
        "    G = nx.Graph()\n",
        "    for city, connections in graph.items():\n",
        "        for neighbor, weight in connections.items():\n",
        "            G.add_edge(city, neighbor, weight=weight)\n",
        "\n",
        "    pos = nx.spring_layout(G)  # Position nodes for a clean layout\n",
        "    nx.draw(G, pos, with_labels=True, node_size=1500, node_color='skyblue', font_size=10, font_weight='bold')\n",
        "    labels = nx.get_edge_attributes(G, 'weight')\n",
        "    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels, font_color='red')\n",
        "    plt.show()\n",
        "\n",
        "# Main execution\n",
        "if __name__ == \"__main__\":\n",
        "    start_city = \"Jeonju\"\n",
        "    end_city = \"Busan\"\n",
        "\n",
        "    # Compute shortest path\n",
        "    distance, path = dijkstra(data, start_city, end_city)\n",
        "    print(f\"Shortest distance from {start_city} to {end_city}: {distance} km\")\n",
        "    print(f\"Path: {' -> '.join(path)}\")\n",
        "\n",
        "    # Plot the graph\n",
        "    plot_graph(data)\n"
      ],
      "metadata": {
        "id": "8C9N_NAZQXpa",
        "outputId": "18c232a9-1c89-42f7-fc7e-0e145717cb5f",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 551
        }
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Shortest distance from Jeonju to Busan: 202 km\n",
            "Path: Jeonju -> Jinju -> Busan\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
```python
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "qQ7kOZHHIJuV"
      },
      "outputs": [],
      "source": [
        "import heapq\n",
        "import networkx as nx\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "landmarks = {\n",
        "    \"Jeonju\": {\n",
        "        \"Daejeon\": 62,\n",
        "        \"Gwangju\": 80,\n",
        "        \"Jinju\": 116\n",
        "    },\n",
        "    \"Jinju\": {\"Jeonju\": 116, \"Busan\": 86},\n",
        "    \"Gwangju\": {\"Jeonju\": 80, \"Daejeon\": 142},\n",
        "    \"Busan\": {\n",
        "        \"Jinju\": 86,\n",
        "        \"Ulsan\": 46,\n",
        "        \"Jeju\": 299\n",
        "    },\n",
        "    \"Ulsan\": {\"Daejeon\": 197, \"Busan\": 46},\n",
        "    \"Jeju\": {\"Busan\": 299},\n",
        "    \"Daejeon\": {\n",
        "        \"Jeonju\": 62,\n",
        "        \"Ulsan\": 197,\n",
        "        \"Gwangju\": 142\n",
        "    }\n",
        "}"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import heapq\n",
        "import networkx as nx\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# Landmarks dictionary\n",
        "data = {\n",
        "    \"Jeonju\": {\"Daejeon\": 62, \"Gwangju\": 80, \"Jinju\": 116},\n",
        "    \"Jinju\": {\"Jeonju\": 116, \"Busan\": 86},\n",
        "    \"Gwangju\": {\"Jeonju\": 80, \"Daejeon\": 142},\n",
        "    \"Busan\": {\"Jinju\": 86, \"Ulsan\": 46, \"Jeju\": 299},\n",
        "    \"Ulsan\": {\"Daejeon\": 197, \"Busan\": 46},\n",
        "    \"Jeju\": {\"Busan\": 299},\n",
        "    \"Daejeon\": {\"Jeonju\": 62, \"Ulsan\": 197, \"Gwangju\": 142}\n",
        "}\n",
        "\n",
        "# Function to implement Dijkstra's algorithm\n",
        "def dijkstra(graph, start, end):\n",
        "    pq = []  # Priority queue\n",
        "    heapq.heappush(pq, (0, start))  # (distance, node)\n",
        "    distances = {node: float('inf') for node in graph}\n",
        "    distances[start] = 0\n",
        "    previous_nodes = {node: None for node in graph}\n",
        "\n",
        "    while pq:\n",
        "        current_distance, current_node = heapq.heappop(pq)\n",
        "\n",
        "        if current_distance > distances[current_node]:\n",
        "            continue\n",
        "\n",
        "        for neighbor, weight in graph[current_node].items():\n",
        "            distance = current_distance + weight\n",
        "            if distance < distances[neighbor]:\n",
        "                distances[neighbor] = distance\n",
        "                previous_nodes[neighbor] = current_node\n",
        "                heapq.heappush(pq, (distance, neighbor))\n",
        "\n",
        "    # Reconstruct the shortest path\n",
        "    path = []\n",
        "    current = end\n",
        "    while current is not None:\n",
        "        path.append(current)\n",
        "        current = previous_nodes[current]\n",
        "    path.reverse()\n",
        "\n",
        "    return distances[end], path\n",
        "\n",
        "# Create and plot the graph\n",
        "def plot_graph(graph):\n",
        "    G = nx.Graph()\n",
        "    for city, connections in graph.items():\n",
        "        for neighbor, weight in connections.items():\n",
        "            G.add_edge(city, neighbor, weight=weight)\n",
        "\n",
        "    pos = nx.spring_layout(G)  # Position nodes for a clean layout\n",
        "    nx.draw(G, pos, with_labels=True, node_size=1500, node_color='skyblue', font_size=10, font_weight='bold')\n",
        "    labels = nx.get_edge_attributes(G, 'weight')\n",
        "    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels, font_color='red')\n",
        "    plt.show()\n",
        "\n",
        "# Main execution\n",
        "if __name__ == \"__main__\":\n",
        "    start_city = \"Jeonju\"\n",
        "    end_city = \"Busan\"\n",
        "\n",
        "    # Compute shortest path\n",
        "    distance, path = dijkstra(data, start_city, end_city)\n",
        "    print(f\"Shortest distance from {start_city} to {end_city}: {distance} km\")\n",
        "    print(f\"Path: {' -> '.join(path)}\")\n",
        "\n",
        "    # Plot the graph\n",
        "    plot_graph(data)\n"
      ],
      "metadata": {
        "id": "8C9N_NAZQXpa"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
```